### ISSUE TITLE
pebble: command not found

### ISSUE THREAD

**Issue by kapiernix** [ltpitt/vagrant-pebble-sdk#2]
I'm working with XUBUNTU 18.04 LTS. Installation seemed to work well (I was amazed by all the things happening on my screen!), but: 'pebble new-project yourprojectname' -> pebble command not found. So something must have gone wrong. I'm lost and ask for help.

**Comment by ltpitt** [comment]
Good afternoon, @kapiernix !

You tried the last version of the code, right?

I will now create my vagrant machien from scratch and check if I have any errors and write again.
I suggest you to do the same (from the repo folder: vagrant destroy and then vagrant up).

**Comment by ltpitt** [comment]
Ok I have just tried from scratch on my Windows 7 and Windows 10 pcs and I had zero issues:
```
Welcome in your Pebble Dev Vagrant Machine.

Have fun, happy hacking.

ubuntu@ubuntu-xenial:~$ pebble
usage: pebble [-h] [--version]
              {sdk,build,clean,install,logs,screenshot,insert-pin,delete-pin,emu
-accel,emu-app-config,emu-battery,emu-bt-connection,emu-compass,emu-control,emu-
tap,emu-time-format,emu-set-timeline-quick-view,emu-set-content-size,ping,login,
logout,repl,transcribe,data-logging,new-project,new-package,kill,wipe,package,an
alyze-size,convert-project,gdb}
```

Sadly I don't have a Linux with Desktop Environment set around at the moment...

Which kind of error do you get?
Whould it be possible for you to paste here the full log that you see when running vagrant up?
Can it be that your internet connection is not perfectly working?

Worst case scenario if you have a remote desktop application I can connect and give a look, if you want.

**Comment by kapiernix** [comment]
Good morning, Itpitt!

Thanks for your quick answer. I made a fresh install yesterday, so I assume it was the last version of the code. I did what you suggested:
This is the log produced by the system itself:
[ubuntu-xenial-16.04-cloudimg-console.log](https://github.com/ltpitt/vagrant-pebble-sdk/files/3544419/ubuntu-xenial-16.04-cloudimg-console.log)
This is the log from what I saw on the screen:
[vagrant.log](https://github.com/ltpitt/vagrant-pebble-sdk/files/3544420/vagrant.log)
My Internet connection should be ok.

**Comment by ltpitt** [comment]
Hi @kapiernix !

I've read your log and I cannot see anything peculiar, I suspect that the issue you describe could be user-related.

Can you please check which users are available in your Vagrant machine?
The code I wrote sets the Pebble SDK and tools for the **ubuntu** user.

It is a bit strange that executing `vagrant ssh` logs you in as **vagrant** user instead of **ubuntu** user (on my Windows PCs it connects using **ubuntu** user, as you can see in my pasted log above).

A simple test could be to try and become the **ubuntu** user:
`sudo su - ubuntu`

and then run the pebble command:
`pebble --version`

**Comment by kapiernix** [comment]
Dear Itpitt,

Ah... That did the trick! 
sudo su - ubuntu cleared the screen and I got the following output:

```
Welcome in your Pebble Dev Vagrant Machine.

Have fun, happy hacking.

ubuntu@ubuntu-xenial:~$ pebble --version
Pebble Tool v4.5 (active SDK: v4.3)
ubuntu@ubuntu-xenial:~$ 
```

Thanks a lot for your support! I still have no idea what's going on in this box but it looks like I'm now ready to program my Pebble smartwatch.

**Comment by ltpitt** [comment]
Happy to read it, @kapiernix !

If the box content is a bit obscure I suggest you to read the Vagrantfile.

Inside this file you can see - in the SCRIPT section - all the commands needed to install a working Pebble SDK Environment.

Maybe also part of that is a bit cryptic, I will put some comments in to better explain what is going on and change the code so that changing to ubuntu user will be automatic when you do a `vagrant ssh`.

Thanks for your feedback, it inspired me to make the provisioning script better and clearer.

Have fun and happy hacking :)
